astra_db:
  collection_name: "chatbotecom"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 5

llm:
  provider: "groq"
  model_name: "meta-llama/llama-4-scout-17b-16e-instruct" 