astra_db:
  collection_name: "chatbotecom"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 5

llm:
  provider: "groq"
  model_name: "deepseek-r1-distill-llama-70b" 